# Generated by Django 2.0.7 on 2019-10-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poduser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=20)),
                ('phoneNumber', models.TextField(default='Phone Number')),
                ('email', models.TextField(default='Email')),
                ('city', models.TextField(default='Montreal')),
                ('country', models.TextField(default='Canada')),
                ('bio', models.TextField(default='Poduser')),
                ('profilePicture', models.TextField(default='Picture')),
            ],
        ),
    ]
