# Generated by Django 2.0.7 on 2019-10-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poduser',
            name='email',
            field=models.EmailField(default='Email', max_length=254),
        ),
    ]
