# Generated by Django 2.0.7 on 2019-10-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0002_auto_20191008_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poduser',
            name='city',
            field=models.CharField(default='Montreal', max_length=20),
        ),
        migrations.AlterField(
            model_name='poduser',
            name='country',
            field=models.CharField(default='Canada', max_length=20),
        ),
        migrations.AlterField(
            model_name='poduser',
            name='phoneNumber',
            field=models.PositiveIntegerField(),
        ),
    ]
