# Generated by Django 2.0.7 on 2019-11-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0002_poduser_trial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poduser',
            name='trial',
        ),
    ]
