# Generated by Django 2.0.7 on 2019-11-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0003_remove_poduser_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poduser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/assets/Mic.jpg', null=True, upload_to=''),
        ),
    ]
