# Generated by Django 2.0.7 on 2019-10-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0003_auto_20191008_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poduser',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='poduser',
            name='phone_number',
            field=models.CharField(default='sdasd', max_length=20),
        ),
    ]
