# Generated by Django 2.0.7 on 2019-10-08 04:20

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0004_auto_20191008_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poduser',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
