# Generated by Django 2.0.7 on 2019-11-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0004_auto_20191111_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_image',
            field=models.ImageField(blank=True, default='Mic.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='podcast_image',
            field=models.ImageField(blank=True, default='url("Mic.jpg")', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='poduser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='Mic.jpg', null=True, upload_to=''),
        ),
    ]
