# Generated by Django 2.0.7 on 2019-10-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0005_auto_20191008_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poduser',
            name='profilePicture',
            field=models.ImageField(upload_to=''),
        ),
    ]
