# Generated by Django 2.0.7 on 2019-10-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0006_auto_20191008_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poduser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
