# Generated by Django 2.0.7 on 2019-10-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0007_auto_20191008_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poduser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poduser',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='poduser',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='poduser',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
