# Generated by Django 2.0.7 on 2019-11-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0007_auto_20191111_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poduser',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='poduser',
            name='password_confirmation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
