# Generated by Django 2.0.7 on 2019-10-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0008_auto_20191008_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poduser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='poduser',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='poduser',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
