# Generated by Django 2.0.7 on 2019-10-08 22:01

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0009_auto_20191008_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poduser',
            name='phone_number',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='poduser',
            name='profilePicture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
