# Generated by Django 2.0.7 on 2019-10-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0010_auto_20191008_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poduser',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
