# Generated by Django 2.0.7 on 2019-11-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0011_auto_20191112_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_image',
            field=models.ImageField(blank=True, default='Mic.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='podcast_image',
            field=models.ImageField(blank=True, default='Mic.jpeg', null=True, upload_to=''),
        ),
    ]
