# Generated by Django 2.0.7 on 2019-10-09 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0011_auto_20191008_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poduser',
            old_name='profilePicture',
            new_name='profile_picture',
        ),
    ]
