# Generated by Django 2.0.7 on 2019-10-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0012_auto_20191009_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poduser',
            name='bio',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
