# Generated by Django 2.0.7 on 2019-10-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0013_auto_20191010_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poduser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
