# Generated by Django 2.0.7 on 2019-10-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0019_auto_20191010_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='poduser',
            options={'ordering': ['name']},
        ),
    ]
