# Generated by Django 2.0.7 on 2019-10-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0020_auto_20191010_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_id', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('published_date', models.CharField(max_length=20, null=True)),
                ('episode_mp3', models.CharField(max_length=20, null=True)),
                ('episode_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={},
        ),
        migrations.AlterModelOptions(
            name='poduser',
            options={},
        ),
        migrations.AddField(
            model_name='podcast',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='podcast_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='podcast',
            name='published_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='poduser',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
