# Generated by Django 2.0.7 on 2019-10-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0021_auto_20191010_2303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
    ]
