# Generated by Django 2.0.7 on 2019-10-10 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0023_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poduser',
            name='username',
        ),
    ]
