# Generated by Django 2.0.7 on 2019-10-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0024_remove_poduser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='poduser',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
