# Generated by Django 2.0.7 on 2019-10-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0025_poduser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('podcast_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=20, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_mp3',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='episode',
            name='podcast_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
