# Generated by Django 2.0.7 on 2019-10-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0027_auto_20191010_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
