# Generated by Django 2.0.7 on 2019-10-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0029_auto_20191011_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='poduser',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
