# Generated by Django 2.0.7 on 2019-10-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0030_poduser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='poduser',
            name='password_confirmation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
