# Generated by Django 2.0.7 on 2019-10-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0031_poduser_password_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poduser',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
