# Generated by Django 2.0.7 on 2019-10-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0033_auto_20191011_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poduser',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
