# Generated by Django 2.0.7 on 2019-10-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0034_auto_20191011_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poduser',
            name='username',
        ),
    ]
