# Generated by Django 2.0.7 on 2019-10-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0035_remove_poduser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='poduser',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='poduser',
            name='password_confirmation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='poduser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='poduser',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='poduser',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True, unique=True),
        ),
    ]
