# Generated by Django 2.0.7 on 2019-10-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0036_auto_20191011_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='poduser',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
