# Generated by Django 2.0.7 on 2019-10-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0037_poduser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
