# Generated by Django 2.0.7 on 2019-10-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0039_auto_20191015_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='author',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
