# Generated by Django 2.0.7 on 2019-10-17 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0043_auto_20191017_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='username',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='podusers.Poduser'),
        ),
    ]
