# Generated by Django 2.0.7 on 2019-10-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0044_auto_20191017_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
