# Generated by Django 2.0.7 on 2019-10-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podusers', '0045_auto_20191018_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_mp3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
